name: Linter CI
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CI: 1

jobs:
  code-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --run "echo" shell.nix
      - name: Handle Rust dependencies caching
        uses: Swatinem/rust-cache@v2
      - name: Lint rust code
        run: |
          nix-shell --run "FMT_OPTS=--check ./scripts/rust-style.sh"
          nix-shell --run "./scripts/rust-linter.sh"
      - name: Lint JS code
        run: nix-shell --run "./scripts/js-check.sh"
      - name: Lint python code
        run: nix-shell --run "black --diff --check test/python"
      - name: Lint Nix code
        run: nix-shell --run "nixpkgs-fmt --check ."
